env:
  browser: true
  es2021: true

extends:
  [
    'airbnb-base',
    'airbnb-typescript/base',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-cheking',
    'prettier',
    'standard-with-typescript'
  ]

overrides: []

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: __dirname
  project: ['./tsconfig.json']

plugins: ['@typescript-eslint', 'unused-imports']

ignorePatterns: ['dist']

settings:
  {
    'import/resolver': { node: { paths: ['src'], extensions: ['.js', '.ts'] } }
  }

rules:
  comma-dangle: ['error', 'never']
  import/extensions: ['error', { js: 'never', ts: 'never' }]
  import/prefer-default-export: off
  max-len:
    - 'error'
    - code: 120
    - ignoreUrls: true
  newline-before-return: -'error'
  no-console: off
  no-param-reassign: [2, { props: false }]
  no-use-before-define: off
  no-void: ['error', { allowAsStatement: true }]
  semi: ['error', 'never']
  unused-imports/no-unused-imports: ['error', 'never']
  unused-imports/no-unused-vars:
    [
      'warn',
      {
        vars: 'all',
        varsIgnorePattern: '^_',
        args: 'after-used',
        argsIgnorePattern: '^_'
      }
    ]
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-use-before-define': ['error']
